export const CLEAR_CART = 'CLEAR_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_ITEM_QUANTITY = 'TOGGLE_ITEM_QUANTITY';
export const UPDATE_PRICE_AND_QUANTITY = 'UPDATE_PRICE_AND_QUANTITY';